import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Autogenerated from the docs/user/ folder tree; ordering/labels come from
// each folder's _category_.json and per-doc sidebar_position frontmatter.
const sidebars: SidebarsConfig = {
  userSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
